import { supabase } from './supabase.js';
import { getOrCreateAnalyticsVisitorId, getOrCreateSessionId } from '../lib/pageAnalytics.js';

/**
 * Order/enquiry/tracking service. Every query here is copied verbatim in
 * structure from the working vanilla implementation (public.js) — not
 * guessed. Verified real orders columns used on insert:
 *   client_name, client_email, project_title, message
 * No project_id, phone, or status column is referenced anywhere in the
 * vanilla app, so none are used here either. The `access_token` returned
 * after insert is generated by the database itself (a column default) —
 * it is never generated client-side.
 *
 * Tracking and messaging never query `orders`/`messages` directly from
 * the browser. They go exclusively through the two RPCs the vanilla app
 * already uses, which is what makes token-based access safe: a visitor
 * can only ever see the single thread their token unlocks, never the
 * full orders table.
 */

/**
 * Creates a new order/enquiry. Returns the inserted row, which includes
 * the DB-generated access_token used for tracking.
 *
 * Also attaches this browser's existing anonymous analytics identity
 * (analytics_visitor_id / analytics_session_id — the SAME visitor_id/
 * session_id already used by visitor_analytics and visitor_engagement,
 * from lib/pageAnalytics.js) so the admin can later see this visitor's
 * browsing engagement alongside the enquiry (PART 16/29) without a
 * second visitor identity ever being created. See
 * supabase/migrations/orders_visitor_link.sql for the two nullable
 * columns this writes to.
 */
export async function createOrder({ client_name, client_email, project_title, message }) {
  const { data, error } = await supabase
    .from('orders')
    .insert([
      {
        client_name,
        client_email,
        project_title,
        message,
        analytics_visitor_id: getOrCreateAnalyticsVisitorId(),
        analytics_session_id: getOrCreateSessionId(),
      },
    ])
    .select()
    .single();

  if (error) throw error;
  return data;
}

/**
 * Fetches a single order's thread via the existing secure RPC. The shape
 * returned by get_order_thread matches the vanilla app's consumption
 * pattern: the first row carries the order-level fields (project_title,
 * created_at, client_message); every row with a non-null `sender` is a
 * message-thread entry (sender: 'admin' | 'client', message).
 * No `status` field is read anywhere in the existing app's use of this
 * RPC, so none is assumed to exist here.
 */
export async function fetchOrderThread(token) {
  const { data, error } = await supabase.rpc('get_order_thread', { p_token: token });
  if (error) throw error;
  return data ?? [];
}

/**
 * Sends a follow-up message on an existing thread via the existing
 * secure RPC.
 */
export async function sendClientMessage(token, message) {
  const { error } = await supabase.rpc('client_send_message', {
    p_token: token,
    p_message: message,
  });
  if (error) throw error;
}

/**
 * Admin-only queries below. These read the `orders` table directly
 * (not through get_order_thread) — safe only because the vanilla admin
 * panel already does exactly this (script.js loadOrders/updateUnreadBadge),
 * which confirms the existing RLS already permits an authenticated admin
 * to read the full orders table. Never call these from public/customer
 * code paths.
 */

/** Total order/enquiry count, for the dashboard summary card. */
export async function fetchOrdersCount() {
  const { count, error } = await supabase
    .from('orders')
    .select('*', { count: 'exact', head: true });
  if (error) throw error;
  return count ?? 0;
}

/**
 * Most recent orders for the dashboard's "recent enquiries" preview.
 * Columns used (client_name, client_email, project_title, message,
 * created_at, admin_read) are verified real columns — visible in the
 * vanilla admin panel's renderOrders()/updateUnreadBadge() — not guessed.
 */
export async function fetchRecentOrders(limit = 5) {
  const { data, error } = await supabase
    .from('orders')
    .select('*')
    .order('id', { ascending: false })
    .limit(limit);
  if (error) throw error;
  return data ?? [];
}

/**
 * Full order/enquiry list for the admin Orders page. Same query shape as
 * fetchRecentOrders but unbounded — the vanilla admin panel's loadOrders()
 * does exactly this (`.from('orders').select('*').order('id', {ascending:
 * false})` with no .limit()).
 */
export async function fetchOrders() {
  const { data, error } = await supabase
    .from('orders')
    .select('*')
    .order('id', { ascending: false });
  if (error) throw error;
  return data ?? [];
}

export async function markOrderRead(orderId) {
  const { error } = await supabase.from('orders').update({ admin_read: true }).eq('id', orderId);
  if (error) throw error;
}

export async function markOrderUnread(orderId) {
  const { error } = await supabase.from('orders').update({ admin_read: false }).eq('id', orderId);
  if (error) throw error;
}

/**
 * Admin-side message thread access. This is deliberately NOT
 * get_order_thread/client_send_message — those RPCs are the token-scoped,
 * customer-facing path. The vanilla admin panel's loadThread()/
 * sendAdminReply() instead read and write the `messages` table directly
 * (order_id, sender, message, created_at), which is only safe here
 * because the caller is already an authenticated, admin_user-verified
 * session — confirmed by reading script.js, not assumed.
 */
export async function fetchOrderMessages(orderId) {
  const { data, error } = await supabase
    .from('messages')
    .select('*')
    .eq('order_id', orderId)
    .order('created_at', { ascending: true });
  if (error) throw error;
  return data ?? [];
}

export async function sendAdminReply(orderId, message) {
  const { error } = await supabase
    .from('messages')
    .insert([{ order_id: orderId, sender: 'admin', message }]);
  if (error) throw error;
}

/**
 * Deletes an order/enquiry. Same operation as vanilla's deleteOrder():
 * `.from('orders').delete().eq('id', orderId)` — row-only. Vanilla never
 * explicitly deletes related `messages` rows for that order, so this
 * doesn't either; if your database has an ON DELETE CASCADE foreign key
 * from messages.order_id to orders.id, that's a backend concern outside
 * what either app's frontend controls.
 */
export async function deleteOrder(orderId) {
  const { error } = await supabase.from('orders').delete().eq('id', orderId);
  if (error) throw error;
}

/**
 * Subscribes to new INSERT events on `messages` for one specific order.
 * Admin-only — the customer-facing path continues to use
 * get_order_thread/client_send_message exclusively and never touches
 * this. Scoped with a Postgres changes filter (`order_id=eq.<id>`) so
 * this subscribes to exactly one enquiry's messages, not the whole
 * table. Returns an unsubscribe function; call it when the enquiry
 * closes, when switching to a different order, or on unmount.
 *
 * Requires Realtime to be enabled for the `messages` table in the
 * Supabase dashboard (Database → Replication) — this cannot be checked
 * or configured from frontend code, so if new messages don't arrive
 * live, that's the first thing to verify there.
 */
export function subscribeToOrderMessages(orderId, onInsert) {
  const channel = supabase
    .channel(`order-messages-${orderId}`)
    .on(
      'postgres_changes',
      { event: 'INSERT', schema: 'public', table: 'messages', filter: `order_id=eq.${orderId}` },
      (payload) => onInsert(payload.new)
    )
    .subscribe();

  return () => {
    supabase.removeChannel(channel);
  };
}
