-- visitor_engagement
-- Active time-on-page / engagement tracking. Additive — does not touch
-- visitor_tracking (service-click counts) or visitor_analytics (one row
-- per page view, no duration). This is a *third*, distinct question
-- ("how long did they actually stay engaged"), so it's a new table
-- rather than a duplicate of either existing one.
--
-- Identity: this table deliberately reuses the SAME anonymous
-- visitor_id/session_id pair already generated by
-- src/lib/pageAnalytics.js (getOrCreateAnalyticsVisitorId /
-- getOrCreateSessionId) and already written to visitor_analytics on
-- every page view. No new visitor identity is introduced. That also
-- means this table can be joined to visitor_analytics on
-- (visitor_id, session_id) for source/device/location context — see
-- src/services/engagementService.js.
--
-- Grain: one row per (browser tab's) page-visit instance, keyed by a
-- client-generated `client_engagement_id` (a UUID minted once when a
-- page becomes the active page, kept for that page visit's whole
-- lifetime). The client repeatedly *upserts* the same row — on a
-- heartbeat, on tab-hide, on inactivity-pause, and on final exit —
-- rather than inserting a new row each time, which is what makes this
-- safe against duplicate/late delivery (network retry, both a
-- `pagehide` and a later `visibilitychange` firing, etc.) without ever
-- double-counting: see upsert_page_engagement below.
-- Run this once in the Supabase SQL Editor.

create table if not exists public.visitor_engagement (
  id bigint generated always as identity primary key,
  client_engagement_id uuid not null unique,
  visitor_id uuid not null,
  session_id uuid not null,
  page_path text not null,
  entered_at timestamptz not null,
  last_activity_at timestamptz not null,
  left_at timestamptz,
  duration_seconds integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists visitor_engagement_visitor_id_idx on public.visitor_engagement (visitor_id);
create index if not exists visitor_engagement_session_id_idx on public.visitor_engagement (session_id);
create index if not exists visitor_engagement_entered_at_idx on public.visitor_engagement (entered_at);
create index if not exists visitor_engagement_page_path_idx on public.visitor_engagement (page_path);

alter table public.visitor_engagement enable row level security;

-- Same "narrow RPC, not a broad table policy" convention as
-- visitor_tracking.sql / visitor_analytics.sql. Only an authenticated
-- admin can read this table directly; anon/authenticated non-admins get
-- nothing, and can never write to it except through the one function
-- below, which can only ever touch the single row identified by the
-- caller-supplied client_engagement_id.
create policy "Admins can view visitor engagement"
  on public.visitor_engagement
  for select
  to authenticated
  using (
    exists (
      select 1 from public.admin_user au
      where au.email = auth.jwt() ->> 'email'
    )
  );

-- Records/updates one page-visit's engagement. Called repeatedly for the
-- same client_engagement_id over the life of a single page visit
-- (heartbeat while active, on visibility change, on final exit).
--
-- Idempotency / anti-double-counting:
--   * `duration_seconds` only ever moves forward (greatest(...)) — a
--     stale/duplicate/out-of-order delivery (e.g. a queued beacon that
--     lands after a newer heartbeat) can never roll the stored duration
--     backward.
--   * `left_at` is only ever set (coalesce keeps the first value) —
--     once a page visit has been marked "left", a late heartbeat that
--     still thinks the page is open cannot resurrect it.
--   * All active-time accounting (pausing on tab-hide, pausing on
--     inactivity) happens client-side in
--     src/lib/engagementTracking.js; this function only ever persists
--     whatever final duration the client computed for this specific
--     client_engagement_id, so the server never has to guess.
create or replace function public.upsert_page_engagement(
  p_client_engagement_id uuid,
  p_visitor_id uuid,
  p_session_id uuid,
  p_page_path text,
  p_entered_at timestamptz,
  p_last_activity_at timestamptz,
  p_duration_seconds integer,
  p_left_at timestamptz default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.visitor_engagement (
    client_engagement_id, visitor_id, session_id, page_path,
    entered_at, last_activity_at, left_at, duration_seconds
  )
  values (
    p_client_engagement_id, p_visitor_id, p_session_id, p_page_path,
    p_entered_at, p_last_activity_at, p_left_at, greatest(0, coalesce(p_duration_seconds, 0))
  )
  on conflict (client_engagement_id) do update set
    last_activity_at = greatest(visitor_engagement.last_activity_at, excluded.last_activity_at),
    left_at = coalesce(visitor_engagement.left_at, excluded.left_at),
    duration_seconds = greatest(visitor_engagement.duration_seconds, excluded.duration_seconds),
    updated_at = now();
end;
$$;

grant execute on function public.upsert_page_engagement(
  uuid, uuid, uuid, text, timestamptz, timestamptz, integer, timestamptz
) to anon, authenticated;

-- Lightweight per-visitor "first seen" directory, used by the admin UI
-- to assign stable "Client 1 / Client 2 / ..." labels (ordered by when
-- each anonymous visitor_id was first ever seen in visitor_analytics —
-- the existing, always-on page-view table — not by engagement data
-- alone, so a visitor is numbered consistently even for visits that
-- predate this feature).
--
-- security invoker (default): only ever sees what the *calling* role's
-- RLS already permits, same reasoning as analytics_overview() in
-- visitor_analytics.sql.
create or replace function public.visitor_directory()
returns table (
  visitor_id uuid,
  first_seen timestamptz,
  last_seen timestamptz
)
language sql
stable
set search_path = public
as $$
  select
    visitor_id,
    min(visited_at) as first_seen,
    max(visited_at) as last_seen
  from public.visitor_analytics
  group by visitor_id
  order by min(visited_at) asc;
$$;

grant execute on function public.visitor_directory() to authenticated;
